# Generated by Django 2.2.5 on 2019-10-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nowaappka', '0002_product_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='nowaappka',
        ),
    ]
